### ISSUE TITLE
Using custom container with AutoValidation

### ISSUE THREAD

**Issue by kvpt** [FluentValidation/FluentValidation.AspNetCore#1]
### FluentValidation.AspNetCore version

11.1.2

### FluentValidation version

11.1.0

### ASP.NET version

.NET 6

### Summary

I don't know if I have to label this as a bug or a feature request because I don't know if it's a desired missing feature or if it's not intended.

Now that the validator factory is deprecated FluentValidation/FluentValidation#1961, there is no way to use another DI container than the .NET one with the AddFluentValidationAutoValidation method.
I tried to redirect the resolves of the validators to my custom container but this don't work because .NET DI doesn't support open generic registrations with a factory method so I'm without alternative.
I will stay on the deprecated way for now but please consider to expose a method to handle this case.

And thank you for your time passed on this amazing project.

### Steps to Reproduce

- Calling AddFluentValidationAutoValidation method
- Using ValidatorFactory property => Deprecated
- No alternative way available inside FluentValidationAutoValidationConfiguration

**Comment by JeremySkinner** [comment]
Hi, thanks for the feedback but this isn't something we'll be adding. The ASP.NET integration will use the IServiceProvider for all service resolution for consistency with the rest of ASP.NET Core going forward. I'd recommend opening a feature request with Microsoft to add this if you need it (if there isn't one already), but you should be prepared to restructure your validators not to rely on this. 

That being said we'll keep `IValidatorFactory` around - all 11.x releases will continue to include it (as deprecated) which you'll be able to use indefinitely, but you'll need to find an alternative approach if/when you decide to upgrade to 12.0

**Comment by JeremySkinner** [comment]
Although, if you have a suggestion for an alternative approach to implement what you want without needing to keep IValidatorFactory around then I'd be happy to consider your proposal.

**Comment by kvpt** [comment]
Thanks for your very fast response.
It was to make sure that it wasn't an oversight.
I have now the confirmation it is not, so like you say I will investigate alternative solution.

If the .NET DI allowed to register open generic with factory, it was piece of cake.
But it doesn't support it and yes there is already an issue on GitHub, this one : https://github.com/dotnet/runtime/issues/41050.
And it will not be solved any time soon, so I will have to be found another solution.

When I have found a satisfactory solution, I will post it here.
