### ISSUE TITLE
As a developer, I would like fluentvalidation middleware to throw exceptions on validation errors

### ISSUE THREAD

**Issue by MoverRud** [FluentValidation/FluentValidation.AspNetCore#10]
### Is your feature request related to a problem? Please describe.

When using auto-validation for fluentvalidation in controllers for asp.net core, the validation will break the request pipeline if a validation error has occured, meaning fluentvalidation will return that validationerror and stop request pipeline.

What I see, is that in some cases, I want to control that myself. So I want the fluentvalidation to throw exceptions whenevar a validation error has occured. 

I want to catch those eceptions myself and do whatevar is needed with that exception in my own middleware. As of the momenent, that is not possible to catch those exceptions.

I cannot se the flag "ThrowOnfailure" which, as far as I can see, a part of the validation strategy. 

So in some way, exposing this flag could be very useful.

### Describe the solution you'd like

I cannot se the flag "ThrowOnfailure" which, as far as I can see, a part of the validation strategy. 

So in some way, exposing this flag could be very useful, so I can use it in the "startup" of a asp.net site / service

**Comment by JeremySkinner** [comment]
Automatic validation integrates with ASP.NET's validation pipeline, the whole purpose of which is to add errors to the `ModelState` collection - it doesn't throw exceptions. This is a feature of ASP.NET Core itself, not of FluentValidation. 

If you want an exception to be thrown you should turn off automatic validation and invoke the validator manually instead.
