### ISSUE TITLE
Populate validation metadata

### ISSUE THREAD

**Issue by danielgreen** [FluentValidation/FluentValidation.AspNetCore#21]
### Is your feature request related to a problem? Please describe.

Raising this issue fully aware that @JeremySkinner won't be maintaining the FV AspNetCore library for much longer...the purpose of the issue is to hopefully have a discussion rather than in expectation of a feature being merged.

In a current development task, I am coding custom tag helpers that will emit form fields.
The intention is for the tag helper to inspect `For.Metadata.IsRequired`; when that property is True then the tag helper will emit a required field asterisk adjacent to the field.

When using the `Required` attribute in data annotations, a metadata provider populates `IsRequired` (and the `ValidatorMetadata` list), but when switching to FluentValidation that's not the case.

I'm interested to learn if @JeremySkinner considered extending FV's ASP.NET integration to populate the metadata.

### Describe the solution you'd like

I've made an attempt at it in a local sandbox app, and it seems to be working albeit after very limited testing.
The solution includes the following:

- `FluentValidationModelMetadataProvider` (subclasses `DefaultModelMetadataProvider`).
- `FluentValidationModelMetadata` (subclasses `ModelMetadata` and wraps a `DefaultModelMetadata`, due to lack of extensibility of the latter).
- `FluentValidationModelMetadataDetails` (subclasses `DefaultMetadataDetails`).
- `FluentValidationMetadataProviderContext` (subclasses `ValidationMetadataProviderContext`).
- `FluentValidationCustomValidationMetadataProvider` (implements `IValidationMetadataProvider`).

In `Program.cs`, before calling `AddFluentValidationAutoValidation`:
```
services.AddSingleton<IModelMetadataProvider, FluentValidationModelMetadataProvider>();

services.Configure<MvcOptions>(options => {
    options.ModelMetadataDetailsProviders.Add(new FluentValidationCustomValidationMetadataProvider());
});
```

### Describe alternatives you've considered

I've previously worked around the lack of metadata by relying on client script to look for `data-val-required` on the element and inject the asterisk, but I would prefer not to rely on this (since client validation might not be enabled, and when it is there's a slight delay while the script runs before the asterisks appear).

### Additional Context

If it's worthwhile I'd be happy to share the code for further discussion or open a PR.

I know the automatic validation approach is discouraged due to its limitations, but for my dev scenarios I still find it incredibly useful. I expect I'll use the metadata population code in future dev projects even if it's not merged into FV itself.

**Comment by JeremySkinner** [comment]
I considered this in the past but in the end decided against it and felt it was out of scope, as the ModelMetadata stuff doesn't directly impact valdiation (as opposed to the ModelValidatorProvider bits). 

That being said if you or other members of the community would consider it valuable and want to develop/support a package that does this then I'd be happy to provide any guidance where necessary and would be happy to link to it from the FluentValidation doc site, although it's not something I'd want to develop/support myself.

**Comment by danielgreen** [comment]
Thanks @JeremySkinner, I'm not sure if there's much or any clamour out there for the feature or if it's just me.

I wouldn't be against developing a small package and would appreciate any guidance you can offer, but if it would have a user base of one then it's probably not worth our time.

In terms of loading the validator inside the tag helper, I don't think I can go that way in my scenario as the tag helpers are being developed in their own NuGet package so can't take that dependency or assume FV is in use.
