### ISSUE TITLE
FluentValidation doesn't work on ASP.NET 6 WebAPI

### ISSUE THREAD

**Issue by krzysztofplazio** [FluentValidation/FluentValidation.AspNetCore#24]
### FluentValidation.AspNetCore version

11.3.0

### FluentValidation version

11.6.0

### ASP.NET version

.NET 6

### Summary

I have a problem with properly set up a Validator. I am doing all stuff in documentation and it's still no works.
I think it is a bug. I created a project by dotnet CLI. 

Here some code.
Program.cs:
`using Hellang.Middleware.ProblemDetails;
using JkpChat.Migrations.Contexts;
using Microsoft.AspNetCore.Mvc.Versioning;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using FluentValidation;
using JkpChat.API.Validators;
using JkpChat.API.Dtos.Messages.Auth;
using JkpChat.API.Repositories;
using JkpChat.API.Services.Hashes;
using JkpChat.API.Services;
using JkpChat.API.Repositories.Hashes;
using FluentValidation.AspNetCore;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);
//builder.Host.ConfigureAppConfiguration(options => options.AddJsonFile("appsettings.json"));

// RFC 7807 - Problem Details
builder.Services.AddProblemDetails(setup =>
{
    setup.IncludeExceptionDetails = (_, _) =>
           builder.Environment.IsDevelopment()
        || builder.Environment.IsStaging();
});

builder.WebHost.UseKestrel(options =>
    options.ListenAnyIP(5000));

// // Set password from user-secrets
// var conStrBuilder = new SqlConnectionStringBuilder(
//         builder.Configuration.GetConnectionString("JkpChatDatabase"))
// {
//     Password = builder.Configuration["Database:Password"],
// };
// builder.Configuration["ConnectionStrings:JkpChatDatabase"] = conStrBuilder.ConnectionString;
// JWT Auth
builder.Services.AddAuthentication(opt => {
    opt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = "http://localhost:5000",
            ValidAudience = "http://localhost:5000",
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["JwtSecret"])),
        };
    });

// Add services to the container.
builder.Services.AddControllers();
// Fluent validation
builder.Services.AddFluentValidationAutoValidation(config => config.DisableDataAnnotationsValidation = true).AddFluentValidationClientsideAdapters();

// API Versioning
builder.Services.AddApiVersioning(o =>
{
    o.AssumeDefaultVersionWhenUnspecified = true;
    o.DefaultApiVersion = new Microsoft.AspNetCore.Mvc.ApiVersion(1, 0);
    o.ReportApiVersions = true;
    o.ApiVersionReader = ApiVersionReader.Combine(
        new QueryStringApiVersionReader("api-version"),
        new HeaderApiVersionReader("X-Version"),
        new MediaTypeApiVersionReader("ver"));
});
builder.Services.AddVersionedApiExplorer(options =>
{
    options.GroupNameFormat = "'v'VVV";
    options.SubstituteApiVersionInUrl = true;
});

// builder.Services.Configure<ApiBehaviorOptions>(options => options.SuppressModelStateInvalidFilter = true);

// Services
builder.Services.AddScoped<IHashService, HashService>();
builder.Services.AddScoped<IContactService, ContactService>();

// Repositories
builder.Services.AddScoped<IContactCredentialRepository, ContactCredentialRepository>();
builder.Services.AddScoped<IChatRepository, ChatRepository>();
builder.Services.AddScoped<IContactRepository, ContactRepository>();

// Automapper
builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

// Fluent validation
builder.Services.AddScoped<IValidator<RegisterContactRequest>, RegisterContactRequestValidator>();
builder.Services.AddValidatorsFromAssemblyContaining<RegisterContactRequestValidator>();

// Cors configuration
builder.Services.AddCors(options =>
{
    options.AddPolicy("EnableCORS", builder =>
    {
        builder.AllowAnyOrigin()
        .AllowAnyHeader()
        .AllowAnyMethod();
    });
});

// DbContext
builder.Services.AddDbContext<JkpChatContext>(
    options =>
        options.UseSqlServer(
            builder.Configuration.GetConnectionString("JkpChatDatabase"),
            x => x.MigrationsAssembly("JkpChat.Migrations")));

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();
app.UseProblemDetails();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseStaticFiles();

app.UseRouting();

app.UseCors("EnableCORS");
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

await app.RunAsync().ConfigureAwait(false);
`
RegisterContactRequestValidator.cs
`using FluentValidation;
using JkpChat.API.Dtos.Messages.Auth;

namespace JkpChat.API.Validators;

public class RegisterContactRequestValidator : AbstractValidator<RegisterContactRequest>
{
    public RegisterContactRequestValidator()
    {
        //RuleFor(x => x.FirstName).NotNull().NotEmpty().MinimumLength(1).MaximumLength(30);
        RuleFor(x => x.FirstName).NotNull();
        RuleFor(x => x.LastName).NotNull().NotEmpty().MinimumLength(1).MaximumLength(30);
        RuleFor(x => x.Username).NotNull().NotEmpty().MinimumLength(3).MaximumLength(50);
        RuleFor(request => request.Password).NotEmpty().MinimumLength(8)
            .Matches("[A-Z]").WithMessage("'{PropertyName}' must contain one or more capital letters.")
            .Matches("[a-z]").WithMessage("'{PropertyName}' must contain one or more lowercase letters.")
            .Matches(@"\d").WithMessage("'{PropertyName}' must contain one or more digits.")
            .Matches(@"[][""!@$%^&*(){}:;<>,.?/+_=|'~\\-]").WithMessage("'{ PropertyName}' must contain one or more special characters.")
            .Matches("^[^£# “”]*$").WithMessage("'{PropertyName}' must not contain the following characters £ # “” or spaces.")
            //.Must(pass => !blacklistedWords.Any(word => pass.IndexOf(word, StringComparison.OrdinalIgnoreCase) >= 0))
            .WithMessage("'{PropertyName}' contains a word that is not allowed.");
        RuleFor(x => x.CountryPhoneCode).NotNull().NotEmpty().MaximumLength(5);
        RuleFor(x => x.PhoneNumber).NotNull().NotEmpty().MaximumLength(9);
        RuleFor(x => x.Address).MaximumLength(50);
        RuleFor(x => x.PostCode).MinimumLength(6).MaximumLength(10);
        RuleFor(x => x.City).MaximumLength(30);
        RuleFor(x => x.BirthDate).GreaterThanOrEqualTo(DateTime.UtcNow.AddYears(-4));
    }
}`

.csproj:

`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1dcde90a-658e-4283-b654-7a315296de70</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="11.6.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.6.0" />
    <PackageReference Include="Hellang.Middleware.ProblemDetails" Version="6.5.1" />
    <PackageReference Include="Meziantou.Analyzer" Version="2.0.62">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.19" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JkpChat.Migrations\JkpChat.Migrations.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json" CopyToPublishDirectory="Always" />
  </ItemGroup>

</Project>
`

### Steps to Reproduce

Just implemented a FluentValidation. All code is above. Thanks in advance

**Comment by JeremySkinner** [comment]
FluentValidation.AspNetCore is tested and works correctly on both asp.net 6 and 7 and is battle tested in production with both. 

If it's not working for you then you've probably not configured something correctly - please review the readme in this repository and ensure you've correctly followed the instructions. 

If after reviewing the documentation thoroughly you still believe you've found a bug then please re-open this issue and provide a minimal, self-contained, runnable sample project that reproduces the problem (as was requested in the issue template). Without a sample project that reproduces the issue I'm afraid I can't help you.
