### ISSUE TITLE
How Can We Disable Data Annotations Without Auto Validation?

### ISSUE THREAD

**Issue by RehanSaeed** [FluentValidation/FluentValidation.AspNetCore#4]
### Is your feature request related to a problem? Please describe.

Auto validation is no longer recommended but the setting to disable data annotations is embedded within it:

```cs
services.AddFluentValidationAutoValidation(x => x.DisableDataAnnotationsValidation = true)
```

We need a new way to disable data annotations.

### Describe the solution you'd like

Perhaps a new fluent method to do this?

**Comment by JeremySkinner** [comment]
Thanks for the suggestion, but I think this is going to be out of scope. 

This is configurable as part of auto-validation as the `FluentValidationObjectModelValidator` can swap out which `ModelValidatorProvider` is being used internally (dataannotations + fluentvalidation, or just fluentvalidation). However if auto-validation isn't enabled then the `FluentValidationObjectModelValidator` isn't being used at all, so there isn't anything to configure. 

You can achieve the same result by disabling the data annotations provider directly, but this is entirely a feature of ASP.NET Core so should be managed with ASP.NET's own configuration, not by FluentValidation. This can be done in your startup's ConfigureServices method as part of your call to AddMvc or AddControllers etc:

```csharp
services.AddMvc(options => 
{
  options.ModelValidatorProviders.Clear();
  // Or you could inspect the collection and remove just the one you don't want. 
});
```
