### ISSUE TITLE
AddFluentValidationAutoValidation doesn't offer an extension to IMvcBuilder like [deprecated] AddFluentValidation

### ISSUE THREAD

**Issue by voigtboy** [FluentValidation/FluentValidation.AspNetCore#6]
### FluentValidation.AspNetCore version

11.2.1

### FluentValidation version

11.2.0

### ASP.NET version

.NET 6

### Summary

before AddFluentValidation was deprecated I called the following:

// controllers
builder.Services.AddControllers()
    // fluent validation on requests coming in
    .AddFluentValidation();

Doing so would require the IMvcBuilder extension. When I converted over to the recommended method .AddFluentValidationAutoValidation() it only allows it to be used on the IServiceCollection interface.  I assume I could do this:

builder.Services.AddFluentValidationAutoValidation().

However, will this not work properly as the other one worked against controllers or "after" controllers were added and an IMvcBuilder was constructed?

### Steps to Reproduce

Just follow the Summary.

**Comment by JeremySkinner** [comment]
It doesn't need to be chained in order to work. Just call them sequentially: https://github.com/FluentValidation/FluentValidation.AspNetCore#automatic-validation

**Comment by voigtboy** [comment]
The last note I would make is that I also registered the validators from an outside assembly like so:

.AddFluentValidation(options => options.RegisterValidatorsFromAssembly(typeof(Library).Assembly, includeInternalTypes: true));

I do not see an equivalent call when using the recommended extension:

.AddFluentValidationAutoValidation( builder => builder.??

**Comment by JeremySkinner** [comment]
Registration is now a separate method so it can be used outside of ASP.NET applications. Can I suggest you take a look at the project readme? This is all covered in there. 

```csharp
services.AddMvc();
services.AddFluentValidationAutoValidation();
services.AddValidatorsFromAssemblyContaining<Library>(includeInternalTypes: true);
```
